server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/rooms/**,/room-service/**
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/members/**,/member-service/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservations/**,/reservation-service/**

